#!/bin/bash

set -e

function follow_links() (
  cd -P "$(dirname -- "$1")"
  file="$PWD/$(basename -- "$1")"
  while [[ -h "$file" ]]; do
    cd -P "$(dirname -- "$file")"
    file="$(readlink -- "$file")"
    cd -P "$(dirname -- "$file")"
    file="$PWD/$(basename -- "$file")"
  done
  echo "$file"
)

this_script="$(follow_links "{BASH_SOURCE[0]}")"
finch_dir="$(dirname "$this_script")"

# Support an interactive mode if no arguments are provided.
#
# 1. Each new line is a separate execution.
# 2. A blank line repeats the last command.
# 3. A line with the word "exit" exits the interactive mode.
if [ $# -eq 0 ]; then
  echo "Welcome to the finch interactive mode."
  echo "Each new line is treated as a separate execution, i.e. \"status\"".
  echo "Type 'exit' to quit."
  last_line="status"
  while true; do
    read -p "finch> " line
    if [ -z "$line" ]; then
      line="$last_line"
    fi
    if [ "$line" = "exit" ]; then
      break
    fi
    eval "set -- $line"
    echo "finch> dart \"$finch_dir/bin/main.dart\" --verbose info --cache $line"
    dart "$finch_dir/bin/main.dart" --verbose info --cache "$@"
    last_line="$line"
  done
  exit 0
fi

dart "$finch_dir/bin/main.dart" \
  --verbose info \
  --cache \
  "$@"
